### ISSUE TITLE
Add Categories to Hamburger menu

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#96]
Add Categories as the top entry in the hamburger menu, and show all categories in the same order as shown on the home page

**Comment by alan345** [comment]
@sanjay-goel need review for the titles and/or design. now we have: 

![image](https://user-images.githubusercontent.com/15246526/44751537-48ba8100-aacd-11e8-9201-4c04e8de06da.png)

**Comment by alan345** [comment]
@sanjay-goel I could not create a new leftSidebar just with hover, because I faced some bugs when you mouse is going from leftSidebar1 to leftSidebar2. here you have the best alternative I could do:

![image](https://user-images.githubusercontent.com/15246526/44970169-2ed1d180-af05-11e8-926e-c99bbbea708d.png)
